// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsReveal")>]
[<assembly: AssemblyProductAttribute("FsReveal")>]
[<assembly: AssemblyDescriptionAttribute("FsReveal parses markdown or F# script files and generates reveal.js slides.")>]
[<assembly: AssemblyVersionAttribute("1.4.0")>]
[<assembly: AssemblyFileVersionAttribute("1.4.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsReveal"
    let [<Literal>] AssemblyProduct = "FsReveal"
    let [<Literal>] AssemblyDescription = "FsReveal parses markdown or F# script files and generates reveal.js slides."
    let [<Literal>] AssemblyVersion = "1.4.0"
    let [<Literal>] AssemblyFileVersion = "1.4.0"
